### ISSUE TITLE
Proposal: restructure interim catalogs

### ISSUE THREAD

**Issue by dalmijn** [Deltares-research/HydroFlows#102]
### Feature type

Changing existing functionality

### Improvement Description

My Idea would be:
Completely separate dedicated forcing, hazard and impact catalogs (or more if that would be necessary in the future).
One general catalog linking to all three of them. 
However I would not list all the files in the general catalog as that's what the dedicated catalogs are for.

### Implementation Description

For the general catalog I'd would think about something like this: 
```yaml
meta: # Maybe not needed
  root: .

Forcings:
  meta: 
    < meta-key >: < some-meta >
  path: < path-to-forcing-catalog >

Hazards:
  meta: 
    < meta-key >: < some-meta >
  path: < path-to-hazards-catalog >

Impacts:
  meta: 
    < meta-key >: < some-meta >
  path: < path-to-impacts-catalog >
```

While a dedicated catalog would preferably look like this (e.g. hazards):
```yaml
meta: # Again maybe not needed
  root: .

event001:
  meta: 
    < meta-key >: < some-meta >
  path: < path-to-hazard-file-001 >
  probability: < probability-of-hazard >
  type: < type-of-hazard-map >

event002:
  meta: 
    < meta-key >: < some-meta >
  path: < path-to-hazard-file-002 >
  probability: < probability-of-hazard >
  type: < type-of-hazard-map >
   
```

### Additional Context

This would entail that some rewriting of code.
