### ISSUE TITLE
create `EventCatalog` class

### ISSUE THREAD

**Issue by DirkEilander** [Deltares-research/HydroFlows#67]
The output of the fluvial and pluvial boundary condition methods and the input for the the sfincs and fiat simulation workflows is based on a description of events. I suggest the following yml format. This is (de)serialized by the `EventCatalog` class

```yaml
version: v0.1
root: /path/to/root/with/csv/files # optional path to look for driver files

events:
  - name: p_rp050
    forcings:
      - type: rainfall
        path: p_rp050.csv  # we check if the file exist
      - type: water_level
         path:  h_rp020.csv
    probability: 0.02 # exceedance probability; optional
  - name: p_rp010
    forcings:
      - type: rainfall
        path: p_rp010.csv
    probability: 0.1
```
