### ISSUE TITLE
create a `HazardCatalog` class

### ISSUE THREAD

**Issue by DirkEilander** [Deltares-research/HydroFlows#85]
Suggestion for `HazardCatalog` class and yml file similar to EventCatalog.

```yaml
version: v0.1

events:
  - name: p_rp050
    hazard:
      - type: flood depth  # allow also for flow velocity or other variables laters
        path: p_rp050.tif
    probability: 0.02       # should this return_period instead of exceedance probability
```
